seed_projects = [
    {
        "id": "1",
        "project_title": "TimeWise",
        "project_description": "A grocery shopping application aiming to revolutionize the experience using dynamic pricing based on shelf life, sentiment analysis for vendors, and recipe recommendations.",
        "project_pdf_link": "Group7_TimeWise_Project_Report_Sem_6.pdf",
        "project_pdf_description": "Project report detailing the TimeWise application, its architecture, and features like dynamic pricing and shelf-life prediction.",
        "project_description_embedding": [],
        "team_members": ["Shraddha Gulati", "Pallavi Bahekar", "Snehil Gupta", "Aditya Kadam", "Samarth Sharma"],
        "year_done": 2024,
        "tech_stack": ["Flutter", "Firebase", "Python", "FastAPI", "MobileNet V2", "Adam Optimizer", "YouTube Transcript API", "Edamam API"]
    },
    {
        "id": "2",
        "project_title": "Guardian Echo",
        "project_description": "An AI-powered system designed to detect distress sounds (like screaming) and automatically alert law enforcement with location data to prevent crime.",
        "project_pdf_link": "Grp 5_GuardianEcho Mini Project Report.pdf",
        "project_pdf_description": "Mini project report on Guardian Echo, focusing on sound classification for personal safety.",
        "project_description_embedding": [],
        "team_members": ["Md Hamid", "Vansh Goel", "A.B Madhava", "Saptarshi Majumder"],
        "year_done": 2024,
        "tech_stack": ["Machine Learning", "Deep Learning", "WaveNet", "CNN", "WhatsApp API"]
    },
    {
        "id": "3",
        "project_title": "JoBro",
        "project_description": "An integrated job portal for companies and students featuring resume parsing, online assessments, and real-time video interviewing capabilities.",
        "project_pdf_link": "Group36_Jobro_Project_Report.pdf",
        "project_pdf_description": "Comprehensive report on the JoBro recruitment platform and its development methodology.",
        "project_description_embedding": [],
        "team_members": ["Abhishek", "Abhishek Pandey", "Deepshikha", "Lavesh Verma", "Sparsh Tandon"],
        "year_done": 2024,
        "tech_stack": ["NEXT.js", "MongoDB", "Supabase", "Socket.IO", "Agora", "Quill Editor", "Python"]
    },
    {
        "id": "4",
        "project_title": "Traffic Sign Detection (Intelli RoadSense)",
        "project_description": "A road safety system utilizing computer vision for vehicle detection, pothole identification, traffic sign recognition, and traffic density analysis.",
        "project_pdf_link": "Group37_TrafficSignDetection_ProjectReport.pdf",
        "project_pdf_description": "Project report on Intelli RoadSense, detailing the use of SSD and CNNs for traffic management.",
        "project_description_embedding": [],
        "team_members": ["Rupesh Singh", "Kumar Abhinav", "Rahul Ranjan", "Shrish Kumar", "Md Kaif Ansari"],
        "year_done": 2024,
        "tech_stack": ["Python", "PyTorch", "OpenCV", "Single Shot Detector (SSD)", "CNN"]
    },
    {
        "id": "5",
        "project_title": "EduHub-AI",
        "project_description": "An AI-integrated online learning platform offering automated assignment generation, personalized difficulty scaling, and live interactive classes.",
        "project_pdf_link": "Group3_EduHub_AI_Project_Report.pdf",
        "project_pdf_description": "Report on EduHub-AI, an educational platform leveraging LLMs and real-time communication tools.",
        "project_description_embedding": [],
        "team_members": ["Sachin Dapkara", "Abhishek Goenka", "Nikhil Ranjan", "Achal Gupta", "Rudranil Acharya"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "Node.js", "Flask", "MongoDB", "Redis", "Socket.IO", "Celery", "Llama-3-70b", "Gemini Pro", "100ms"]
    },
    {
        "id": "6",
        "project_title": "LabourLink",
        "project_description": "A workforce management and scheduling platform designed to optimize employee scheduling, resource allocation, and labor costs using AI algorithms.",
        "project_pdf_link": "Group_6__LabourLink.pdf",
        "project_pdf_description": "Project report for LabourLink, focusing on efficient work service providing and scheduling.",
        "project_description_embedding": [],
        "team_members": ["Naveen Uikey", "Prince Aharwal", "Deepak Singh", "Shashank Karoria"],
        "year_done": 2024,
        "tech_stack": ["Cloud Infrastructure", "Machine Learning", "AI Algorithms", "Predictive Analytics"]
    },
    {
        "id": "7",
        "project_title": "QuickStaff",
        "project_description": "An ML-enhanced home service platform that connects users with service providers and utilizes an AI chatbot for user assistance.",
        "project_pdf_link": "Group_4_QuickStaff.pdf",
        "project_pdf_description": "Report detailing QuickStaff, a platform for hiring home service professionals with AI integration.",
        "project_description_embedding": [],
        "team_members": ["Vivek Korah", "Amit Vikram Singh", "Aryan Wadhe", "Vineet Kumar Verma", "Vishal Kumar"],
        "year_done": 2024,
        "tech_stack": ["React.js", "Node.js", "Express.js", "GraphQL", "MongoDB", "Three.js", "IBM Watson Assistant", "Hygraph", "Descope"]
    },
    {
        "id": "8",
        "project_title": "Filit",
        "project_description": "An automated micro-savings and investment application that rounds off transactions to invest spare change into assets like digital gold.",
        "project_pdf_link": "Group8_Filit_Automated_MicroSavings_and_Investment_Platform.pdf",
        "project_pdf_description": "Project report on Filit, a fintech application for automated savings and investments.",
        "project_description_embedding": [],
        "team_members": ["Gaurav Kabra", "Md. Mazahar Pasha Lathi", "Advit Mahale", "Rhysha Kachari", "Animesh Sahu"],
        "year_done": 2024,
        "tech_stack": ["Flutter", "Django", "PostgreSQL", "Python", "PhonePe API", "Augmont API"]
    },
    {
        "id": "9",
        "project_title": "PawfectPals",
        "project_description": "A dog vaccination tracker and identification system using nose print analysis powered by deep learning models.",
        "project_pdf_link": "Group 35_Dog Vaccination Tracker using Nose Print Analysis.pdf",
        "project_pdf_description": "Report on PawfectPals, a mobile app using VGGNet for dog identification and welfare management.",
        "project_description_embedding": [],
        "team_members": ["Saumya", "Aditya Tripathi", "Priyanshu Dubey", "Rushi Mahajan"],
        "year_done": 2024,
        "tech_stack": ["Deep Learning", "VGGNet (CNN)", "Python", "Image Processing"]
    },
    {
        "id": "10",
        "project_title": "Influencia",
        "project_description": "A freelancing platform specifically designed to connect social media influencers with brands for project collaboration.",
        "project_pdf_link": "Group_2 _ One above all .pdf",
        "project_pdf_description": "Project report for Influencia, detailing the development of an influencer marketplace.",
        "project_description_embedding": [],
        "team_members": ["Aryan Raj Singh", "Prashant Kumar", "Karan Trivedi", "Aanand Surana", "Admya Maini"],
        "year_done": 2024,
        "tech_stack": ["React.js", "Node.js", "Express.js", "GraphQL", "MongoDB", "Three.js", "Tailwind CSS", "IBM Watson Assistant"]
    },
    {
        "id": "11",
        "project_title": "MED - CHAIN : Revolutionizing Healthcare Distribution with Blockchain Technology",
        "project_description": "The MED-CHAIN project utilizes blockchain technology to create a decentralized ledger system for the pharmaceutical supply chain. Its primary goal is to address the complexities and challenges of the pharmaceutical supply chain, such as counterfeiting, lack of transparency, and inefficiency. The system ensures complete transparency and traceability, tracking each medical drug from production to consumption. This enhanced security and trust is facilitated through the immutable recording of transactions and the use of smart contracts. Future plans include expansion to other healthcare supplies, integration with IoT devices for real-time monitoring, and implementation of AI/Machine Learning algorithms for predictive analytics.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_1_Report_MED-CHAIN.pdf",
        "project_description_embedding": [],
        "team_members": ["Atharva Arya", "Dhananjay Rathod", "Mohit Prajapati", "Utkarsh Pawar", "Dhruv Fonia"],
        "year_done": 2024,
        "tech_stack": ["Blockchain", "Smart Contracts (Solidity)", "Truffle Framework", "Ethereum Developer Tools (Ganache, Metamask, Etherscan)"]
    },
    {
        "id": "12",
        "project_title": "TakeMoney - Smart Loan Risk Mitigation Software",
        "project_description": "TakeMoney is an AI-driven, blockchain-based mobile application designed to enhance borrower risk assessment and mitigate loan defaults. It integrates conventional financial data (credit scores, income, debt-to-income ratios) with non-traditional data from personality assessments to provide a comprehensive risk profile. The core features include Advanced Machine Learning for prediction, Blockchain Security for decentralized data storage (using Polygon Edge), Personalized Risk Mitigation advice, and Proactive Customer Support. The methodology involves using Principal Component Analysis (PCA) for dimensionality reduction and XGBoost for high predictive accuracy.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_21_Smart_Loan_Risk_Evaluation_Software.pdf",
        "project_description_embedding": [],
        "team_members": ["Samanwith KSN", "Badrinath Akkala", "Sharath Chandra", "Kiranmaye", "Rushendra"],
        "year_done": 2024,
        "tech_stack": ["Machine Learning (PCA, XGBoost)", "Blockchain (Polygon Edge, decentralized network)", "Flask REST API", "Android App"]
    },
    {
        "id": "13",
        "project_title": "Audio Visual Alchemy: An AI-Driven Multimedia Transformation and Conversational Interface Platform",
        "project_description": "This project is a multi-modal AI platform integrating cutting-edge models for creative content generation and human-computer interaction. Its features include: Image generation using the Stable Diffusion model; Face swapping in images using the ROOP model; Lip sync in videos using the Lip2Sync model; and a Conversational Interface (Chatbot and Question Answering system) utilizing the CRISP model for natural language processing. The platform is designed to provide unprecedented creative freedom and seamless user interaction capabilities.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group 43 Audio Visual alchemy mini project report.pdf",
        "project_description_embedding": [],
        "team_members": ["Govind Patidar", "Anshu Verma"],
        "year_done": 2024,
        "tech_stack": ["AI (Stable Diffusion, ROOP, Lip2Sync, CRISP)", "Deep Learning", "Natural Language Processing"]
    },
    {
        "id": "14",
        "project_title": "CodeSphere's VisionPark: Parking Slot Detection with Computer Vision",
        "project_description": "VisionPark is a computer vision-based solution for accurate and cost-effective parking slot detection, overcoming the limitations of traditional infrared sensor systems. It employs strategically placed CCTV cameras that feed real-time footage to a Raspberry Pi. The system uses two models: Model1 uses grayscale analysis to detect occupancy based on pixel density, and Model2 uses advanced deep learning algorithms to accurately classify cars, empty slots, and other objects, improving reliability. The system indicates slot status using LED lights (green for vacant, red for occupied).",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group 45 CodeSphere's Vision Park_LCI2021036.pdf",
        "project_description_embedding": [],
        "team_members": ["Shubham Singh"],
        "year_done": 2024,
        "tech_stack": ["Computer Vision", "Machine Learning (Image Classification)", "Raspberry Pi", "Python", "OpenCV", "ScikitLearn/TensorFlow"]
    },
    {
        "id": "15",
        "project_title": "IIITL EduSense - Revolutionizing College Management with Advanced Proctoring and LMS",
        "project_description": "IIITL EduSense is a transformative college management system that integrates an advanced Online Proctoring System with a comprehensive Learning Management System (LMS). The Online Proctoring System (ProctoAI) ensures the integrity of remote examinations using AI-driven detection algorithms (e.g., Al-driven detection of cheating behaviors like mobile phone usage and multiple face detection) and real-time monitoring. The LMS component allows educators to manage courses, administer assessments, and track student progress, enhancing the overall learning experience. The system uses JSON Web Tokens (JWT) and bcryptjs for secure authentication and role management.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group 15_IIITL EduSense Project Report.pdf",
        "project_description_embedding": [],
        "team_members": ["Tridibesh Misra", "Ayush Sharma", "Apoorv Shrivastava", "Hardik Khandelwal", "Lovisha Bhatia"],
        "year_done": 2024,
        "tech_stack": ["AI-driven Proctoring", "Learning Management System (LMS)", "Node.js", "Express.js", "React.js (Frontend)", "MongoDB", "Django (Backend for CMS)", "PostgreSQL (Database for CMS)", "COCO-SSD Model"]
    },
    {
        "id": "16",
        "project_title": "IZRAF - Counterfeit Item Validator",
        "project_description": "A blockchain-based web application designed to combat counterfeit products by empowering consumers and authorities to verify product authenticity using unique QR codes and immutable ledger technology.",
        "project_pdf_link": "Group 39 - IZRAF - Project Report.pdf",
        "project_pdf_description": "Project report detailing the development of IZRAF, a solution using Ethereum blockchain and smart contracts to ensure supply chain transparency and product verification.",
        "project_description_embedding": [],
        "team_members": ["Abhinash Kumar", "Protyay Mondal", "Aryan Kaushal", "Adarsh Kumar", "Vikrant Kumar Sharma"],
        "year_done": 2024,
        "tech_stack": ["ReactJS", "Node.js", "Solidity", "Truffle", "Ganache", "Web3.js", "Ethereum"]
    },
    {
        "id": "17",
        "project_title": "Decentralized AI for Medical Diagnostics",
        "project_description": "An automated medical insurance claims service system utilizing blockchain to facilitate secure, transparent, and efficient information exchange between patients, hospitals, and insurance companies.",
        "project_pdf_link": "Group 40 - Decentralized AI for Medical DIagnostics.pdf",
        "project_pdf_description": "Report on a blockchain-based healthcare system that automates claims and secures medical records using smart contracts and decentralized storage.",
        "project_description_embedding": [],
        "team_members": ["Harsh Golchha", "Harshdeep Singh Batra", "Dev Shah", "Dhruva N L Choudhary", "Devasoth Bukya Kranthi"],
        "year_done": 2024,
        "tech_stack": ["Flutter", "Node.js", "Hardhat", "Sepholia", "Infura", "Solidity"]
    },
    {
        "id": "18",
        "project_title": "VisionTuner",
        "project_description": "A framework and web platform for object detection and classification that allows users to fine-tune YOLO models for specific domains and datasets without deep technical expertise.",
        "project_pdf_link": "Group No. 18 - Vision-Tuner Project Report- IIITL _ 2021 Batch ( 6th Sem Mini Project ).pdf",
        "project_pdf_description": "Project report for VisionTuner, a tool enabling users to upload datasets and train custom computer vision models using an improved YOLO architecture.",
        "project_description_embedding": [],
        "team_members": ["Lokesh Dandamudi", "Ajay Maheshwari", "Sahil Pandey", "Mahek Jain", "Vasa Narendra Kumar"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "Flask", "MongoDB", "YOLOv5", "PyTorch", "Cloudinary"]
    },
    {
        "id": "19",
        "project_title": "Get Proctored AI",
        "project_description": "An AI-enhanced platform for monitoring online examinations using facial recognition and object detection to identify violations, along with tools for automated test creation.",
        "project_pdf_link": "Group 12 - SAIL - Get Proctored AI.pdf",
        "project_pdf_description": "Report detailing an online proctoring system that uses computer vision to detect phones, multiple faces, and tab switching during exams.",
        "project_description_embedding": [],
        "team_members": ["Sahil Singh", "Chakradhar Reddy", "Annu Priya", "Savarna Chandra", "Aryaman Shukla"],
        "year_done": 2024,
        "tech_stack": ["MediaPipe", "TensorFlow", "Gemini LLM", "React"]
    },
    {
        "id": "20",
        "project_title": "Startup Sync",
        "project_description": "A comprehensive solution to streamline sales and procurement operations for startups, featuring AI-powered vendor recommendations, employee analytics, and sales forecasting.",
        "project_pdf_link": "Group 14- Startup Sync- Project Report.pdf",
        "project_pdf_description": "Project report on Startup Sync, a platform utilizing machine learning models like XGBoost and LSTM to optimize business processes for emerging ventures.",
        "project_description_embedding": [],
        "team_members": ["Sumit Raj", "Ria Malvi", "Shruti Gajbhiye", "Manan Chawla", "Sakshi Sharma"],
        "year_done": 2024,
        "tech_stack": ["Random Forest Regression", "LSTM", "XGBoost", "Microservices", "RDBMS"]
    },
    {
        "id": "21",
        "project_title": "E-commerce Rental Portal (KIR.AI)",
        "project_description": "A rental platform for assets like houses and vehicles that integrates Augmented Reality (AR) for virtual tours and voice navigation for enhanced user accessibility.",
        "project_pdf_link": "Group 16 -e-Commerce Portal.pdf",
        "project_pdf_description": "Report describing a rental marketplace that leverages Unity for AR experiences and Alan AI for voice commands to improve the user booking experience.",
        "project_description_embedding": [],
        "team_members": ["Milind Palaria", "Ashish Bhardwaj", "Harsh Kanojia", "Rishav Kumar", "Avinash Krishna"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "Firebase", "Alan AI", "Unity", "Tailwind CSS"]
    },
    {
        "id": "22",
        "project_title": "Smart Fitness",
        "project_description": "A comprehensive health and fitness tracking mobile application that tracks activity, meals, and sleep, and uses ML for image-based body progress tracking.",
        "project_pdf_link": "Group No 38 - Smart Fitness Fitness Tracking App.pdf",
        "project_pdf_description": "Project report for a mobile fitness app built with Flutter that provides analytics on health metrics and personalized workout routines.",
        "project_description_embedding": [],
        "team_members": ["Amartya Maurya", "Muskan", "Sahil Kumar", "Utkarsh Mishra"],
        "year_done": 2025,
        "tech_stack": ["Flutter", "MySQL", "Dart", "Firebase"]
    },
    {
        "id": "23",
        "project_title": "FlavourAlchemy",
        "project_description": "An AI-driven culinary platform offering recipe generation and ingredient identification using image recognition and user preference analysis.",
        "project_pdf_link": "Group No. 9-Flavor Alchemy - Project Report.pdf",
        "project_pdf_description": "Report on an AI application that uses Encoder-Decoder models and Transformers to generate recipes from food images and ingredient labels.",
        "project_description_embedding": [],
        "team_members": ["Sanskriti", "Ashwani Dhiman", "Anirudh Rana", "Yogesh Kumar", "Hima Bindu"],
        "year_done": 2024,
        "tech_stack": ["CNN", "Transformers", "PyTorch", "Encoder-Decoder Models"]
    },
    {
        "id": "24",
        "project_title": "Bargain Bay",
        "project_description": "A dynamic reselling marketplace facilitating secure blockchain payments, AI-assisted product comparisons, and real-time communication between buyers and sellers.",
        "project_pdf_link": "Group No. 13- Bargain_Bay.pdf",
        "project_pdf_description": "Project report for Bargain Bay, a reselling platform featuring negotiation capabilities, video chat, and crypto payments.",
        "project_description_embedding": [],
        "team_members": ["Shweta", "Deepak Chattwani", "Shivi Gupta", "M. Dinesh", "Shivam"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "TypeScript", "Gemini API", "Supabase", "ZEGOCLOUD", "Solidity"]
    },
    {
        "id": "25",
        "project_title": "MARS: Make Athletes Reach Success",
        "project_description": "A Web3-based crowdfunding platform designed to help athletes raise funds through secure blockchain transactions and NFT auctions.",
        "project_pdf_link": "Group 49 - MARS (Web3 crowdfunding).pdf",
        "project_pdf_description": "Report on MARS, a decentralized platform connecting athletes with backers using Ethereum smart contracts and community chat features.",
        "project_description_embedding": [],
        "team_members": ["Aryan Kumar", "Prajjwal Suhane", "Kanishk Dadhich", "Saksham Nagpal", "Md Faizan"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "TypeScript", "Solidity", "Hardhat", "Thirdweb", "Node.js", "Socket.io"]
    },
    {
        "id": "26",
        "project_title": "InterVueSense: Redefining Interviews with AI",
        "project_description": "An AI-powered recruitment platform that streamlines hiring through automated resume analysis, AI-driven interviews, and sentiment/emotional analysis of audio and video inputs.",
        "project_pdf_link": "Group_17_InterVueSense_project_report.pdf",
        "project_pdf_description": "Project report detailing a recruitment system utilizing OpenAI, OpenCV, and Flask to conduct and analyze candidate interviews automatically.",
        "project_description_embedding": [],
        "team_members": ["Perumall Pardhiv", "Guntha Vishal Kumar", "Thallam Sai Vasanth", "Vamshi Krishna", "Harini Manche"],
        "year_done": 2025,
        "tech_stack": ["Python", "Flask", "MongoDB", "TypeScript", "Next.js", "OpenAI API", "OpenCV", "Hugging Face API", "Google Cloud API"]
    },
    {
        "id": "27",
        "project_title": "Guardian AI - Mental Health Gen-AI",
        "project_description": "A web-based mental health platform designed for suicide prevention, featuring AI chat therapy, mood tracking, and stress management tools like breathing pulses.",
        "project_pdf_link": "Group No. 47 GuardianAI by team Nexus.pdf",
        "project_pdf_description": "Report on a mental health application utilizing Gen-AI and modern web frameworks to provide accessible emotional support.",
        "project_description_embedding": [],
        "team_members": ["Dhruv Sangra", "Abhishek Bradwal", "Kundan Pratap S"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "tRPC", "Prisma", "HuggingFace", "LangChain"]
    },
    {
        "id": "28",
        "project_title": "ThinkSync",
        "project_description": "A real-time collaborative platform integrating a virtual whiteboard, video calling, and chat, enhanced with AI-based image generation for seamless remote teamwork.",
        "project_pdf_link": "Group No.11- ThinkSync (Collaborative team-work website).pdf",
        "project_pdf_description": "Project report describing a comprehensive collaboration suite built with Next.js and real-time socket technologies.",
        "project_description_embedding": [],
        "team_members": ["Rahul", "Om", "Shashwat", "Lakshay", "Shubhranshu"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "TypeScript", "Node.js", "Socket.io", "Prisma", "Supabase", "LiveKit", "Clerk", "OpenAI"]
    },
    {
        "id": "29",
        "project_title": "CUTS - Salon Management & Booking System",
        "project_description": "A salon discovery and booking web application featuring a dynamic queue management system and an AI-powered virtual hairstyle try-on feature.",
        "project_pdf_link": "Group No. 48 - Salon Management and Booking System.pdf",
        "project_pdf_description": "Report detailing a salon management system that uses the Segment Anything Model (SAM) for virtual try-ons and MongoDB for real-time queue updates.",
        "project_description_embedding": [],
        "team_members": ["Shivam Pratap Singh", "Pawan Maheshwari", "Vibhor Gupta", "Sanskar Goel", "Mayank Agarwal"],
        "year_done": 2024,
        "tech_stack": ["Next.js", "MongoDB", "Tailwind CSS", "Python", "Segment Anything Model (SAM)", "Razorpay"]
    },
    {
        "id": "30",
        "project_title": "Finderr: LLM powered College Enquiry Chatbot",
        "project_description": "Finderr is a Large Language Model (LLM)-powered college enquiry chatbot that uses Retrieval Augmented Generation (RAG) architecture to answer user queries with accurate, context-rich information scraped from the college website. This aims to simplify accessing college-related information and overcome the LLM drawback of 'hallucinations' by providing a knowledge base. Key features include Query Resolution, Knowledge Base Integration, Role-Based Access Control, a Feedback Mechanism, and Multi-Turn Dialogue Management.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_41_Finderr_project_report.pdf",
        "project_description_embedding": [],
        "team_members": ["Dilip Patnana", "Sanchit Gupta", "Prateek Mohan", "Narendula Grishma"],
        "year_done": 2024,
        "tech_stack": ["LLM (GPT 3.5)", "RAG (Retrieval Augmented Generation)", "LlamaIndex", "Beautiful Soup (for data scraping)", "HTML/CSS/JavaScript", "Particle JS", "Vector Store Index"]
    },
    {
        "id": "31",
        "project_title": "Echo Collab",
        "project_description": "ECHO Collab is a cutting-edge, AI-powered project management platform that redefines collaborative work environments. It is built using the MERN stack, Supabase, and Django. Key features include: dynamic project carousels, seamless integrations, video conferencing (via GetStream.io and Clerk), task management, and an AI Chatbot powered by LLMs, NLP, and a Retrieval Augmented Generation (RAG) approach. The platform also includes a robust user authentication system with JWT and Cloudinary for image storage, and an NLP-based resume builder/parser.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_42_ECHO_Collab_mini_project.pdf",
        "project_description_embedding": [],
        "team_members": ["Umm E Kulsum", "Divyanshi Chouksey", "Arpita Jena"],
        "year_done": 2024,
        "tech_stack": ["MERN Stack (MongoDB, Express.js, React, Node.js)", "Supabase", "Django", "JWT", "Cloudinary", "GetStream.io", "Clerk (for video conferencing)", "AI/LLM (GPT-Index, LangChain)", "NLP (spaCy, NLTK)"]
    },
    {
        "id": "32",
        "project_title": "MedInsight: Revolutionizing Medical Reporting with AI",
        "project_description": "MedInsight is a groundbreaking project that utilizes AI technology to enhance the efficiency and accuracy of medical documentation. Its primary services are AI-assisted report summarization (leveraging Amazon Comprehend Medical and Gemini API) and intelligent data extraction from voluminous medical records. Additionally, it offers AI-powered diagnostic features for Brain Tumor Detection from MRIs and Chest X-ray Pneumonia Detection (using ML models and Kaggle datasets). The goal is to streamline the reporting process and improve patient care outcomes.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_44_MedInsight_Project_Report.pdf",
        "project_description_embedding": [],
        "team_members": ["Yuvraj Madhav Byale", "Ritesh Mohan", "Khush Makwana", "Tejas Sankhla", "Varad Jadhav"],
        "year_done": 2024,
        "tech_stack": ["AI/ML", "Natural Language Processing (NLP)", "Amazon Comprehend Medical", "Gemini API", "Tesseract module (Javascript)", "Kaggle (for datasets)"]
    },
    {
        "id": "33",
        "project_title": "ScanGuard: Redefining Student Attendance with RFID and Facial Recognition",
        "project_description": "ScanGuard is an automated attendance tracking system designed for educational institutions to eliminate manual entry errors and proxy attendance. The system uses a dual-layered approach: initial detection is done by a UHF RFID reader scanning tags in student ID cards, and this is complemented by Facial Recognition technology for identity verification. The face recognition model uses Convolutional Neural Networks (CNNs) and the Histogram of Oriented Gradients (HOG) algorithm. The system uses a Raspberry Pi to manage the RFID reader workload.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group_33_ScanGuard_Project_Report .pdf",
        "project_description_embedding": [],
        "team_members": ["Anikate Koul", "Arya Singh"],
        "year_done": 2024,
        "tech_stack": ["RFID (UHF RFID reader)", "Facial Recognition", "AI (CNN, HOG)", "Python (face-recognition, dlib libraries)", "Raspberry Pi"]
    },
    {
        "id": "34",
        "project_title": "Personalized SaaS Companion",
        "project_description": "An AI-powered agent designed to revolutionize social media marketing, particularly benefiting small startups by automating content creation and personalizing it to match unique user writing styles. It collects trending social media posts via the Selenium API and retrieves user's historical posts. The post generation process leverages the Retrieval-Augmented Generation (RAG) framework, Pinecone Vector Database, and the Mistral Large Language Model (LLM) to deliver tailored, trend-based, and efficient content. The front end is built with Next.js, and data is stored in MongoDB and Pinecone.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group10_Personalized_saas_companion.pdf",
        "project_description_embedding": [],
        "team_members": ["Saarthak Verma", "Parth Verma", "Pranjal Adwani", "Prateek Parmar", "Gaurav Mishra"],
        "year_done": 2024,
        "tech_stack": ["AI/LLM (Mistral LLM)", "RAG (Retrieval-Augmented Generation)", "Pinecone Vector Database", "MongoDB", "Next.js", "Selenium API", "Flask"]
    },
    {
        "id": "35",
        "project_title": "RiverWatch: Monitoring Water Quality In U.P.",
        "project_description": "RiverWatch is a project for real-time monitoring of river water quality across Uttar Pradesh, India. It uses a network of sensors to collect data on key parameters like Total Coliform Organisms, Dissolved Oxygen (DO), Biochemical Oxygen Demand (BOD), and temperature. This data is analyzed by algorithms and categorized into five quality levels (A to E). The project features a user-friendly website where users can input locations (using OpenStreetMap API for coordinates) to get instant water quality status.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "Group-46-river-water-monitring-1.pdf",
        "project_description_embedding": [],
        "team_members": ["Aditya Sharma", "Ashwin Ekka", "Ashmit Raj", "Devesh Kailodiya"],
        "year_done": 2024,
        "tech_stack": ["Sensor Technology", "Geospatial Analysis", "Data Analytics", "OpenStreetMap API", "Google Maps API", "Algorithms for water quality categorization"]
    },
    {
        "id": "36",
        "project_title": "SYNK - Enhancing Privacy With Zero Knowledge Proof",
        "project_description": "Synk is a command-line tool that enables secure and verifiable inference for deep learning models and computational graphs using Zero-Knowledge Machine Learning (ZKML) techniques. It acts as a compiler, transforming AI/ML models into a zero-knowledge proof format, primarily using the Halo-2 zk-SNARK proof system. This allows users to verify a model’s prediction correctness without revealing the underlying model or data, thereby addressing concerns over transparency, fairness, and privacy in AI systems. The tool leverages zero-knowledge proofs and homomorphic encryption.",
        "project_pdf_link": "N/A",
        "project_pdf_description": "group30_board-3_synk.pdf",
        "project_description_embedding": [],
        "team_members": ["Palash Baderia", "Prince Singh", "Apoorva Kothari", "Karthik S", "Aditya Yadav"],
        "year_done": 2024,
        "tech_stack": ["Zero-Knowledge Machine Learning (ZKML)", "Cryptography (Zero-Knowledge Proofs, Homomorphic Encryption)", "Halo-2 (zk-SNARK proof system)", "Rust (Programming Language)", "Blockchain (for metadata storage)", "ONNX (model format)"]
    }
]